# This is a config for E2B sandbox template.
# You can use template ID (atqlszexk38u8zzg34r4) or template name (nebula-nextjs-test2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("nebula-nextjs-test2") # Sync sandbox
# sandbox = await AsyncSandbox.create("nebula-nextjs-test2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('nebula-nextjs-test2')

team_id = "a8da650a-5935-4121-8923-dd915ab226ca"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "nebula-nextjs-test2"
template_id = "atqlszexk38u8zzg34r4"
